name: Build OSTree Image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create OSTree Directory
        run: |
          mkdir -p ${{ github.workspace }}/ostree-repo
          mkdir -p ${{ github.workspace }}/custom-root
          chmod -R 777 ${{ github.workspace }}/ostree-repo
          chmod -R 777 ${{ github.workspace }}/custom-root

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build OSTree Image
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/ostree-repo:/repo \
            -v ${{ github.workspace }}/custom-root:/mnt \
            opensuse/tumbleweed /bin/sh -c '
            zypper --non-interactive install ostree neofetch && \
            ostree init --repo=/repo && \
            ostree commit --repo=/repo --branch=ma_branche --tree=dir=/mnt
            '

      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/live'
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          image: opensuse/tumbleweed
          tags: ghcr.io/${{ steps.convert_username.outputs.username_lowercase }}/ostree-image:latest
          registry: ${{ steps.registry_case.outputs.lowercase }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/live'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
