name: Mises à jour OSTree
on:
  push:
    branches:
      - main
      
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.txt"
  # Build when manually triggering this workflow for a branch. This allows you
  # to build any branch, even if it's not listed in the automated triggers above.
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code source
        uses: actions/checkout@v2

      - name: Installer Docker
        uses: docker/setup-buildx-action@v1

      - name: Construire l'image MicroOS personnalisée
        run: |
          docker run --rm -v $PWD:/workspace -w /workspace opensuse/leap:latest bash -c "zypper --non-interactive install -y wget && wget https://github.com/openSUSE/kiwi/releases/download/9.23.8/kiwi-9.23.8-1.x86_64.rpm && zypper --non-interactive install -y kiwi-9.23.8-1.x86_64.rpm && git clone https://github.com/openSUSE/microOS-desktop.git && cd microOS-desktop && sudo kiwi-ng --type ostree system build --description kiwi-desc-netboot && sudo mv result/* /workspace"

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build et push de l'image OSTree vers GHCR
        run: |
          docker buildx create --use --name ostree
          docker buildx build --push --platform linux/amd64 --tag ghcr.io/$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')/${{ github.repository_name }}:latest .
