name: Build and Upload OSTree Image

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v1

    - name: Build and upload image
      run: |
        docker build -t ostree-image .
        docker run -e GHCR_TOKEN="${{ secrets.GITHUB_TOKEN }}" -e GHCR_REPOSITORY="${{ github.actor }}/your-repo" ostree-image
