name: Mises à jour OSTree
on:
  push:
    branches:
      - main
      
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.txt"
  # Build when manually triggering this workflow for a branch. This allows you
  # to build any branch, even if it's not listed in the automated triggers above.
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Set up openSUSE container
        run: |
          podman run -d --name opensuse-container opensuse/leap:latest tail -f /dev/null

      - name: Copy kiwi-ng configuration
        run: |
          podman cp /etc/kiwi-ng/opensuse-container.conf opensuse-container:/etc/kiwi-ng/opensuse-container.conf

      - name: Update repository
        run: |
          podman exec opensuse-container zypper --gpg-auto-import-keys --non-interactive refresh

      - name: Install kiwi-tools
        run: |
          podman exec opensuse-container zypper --non-interactive install kiwi kiwi-tools

      - name: Copy kiwi description
        run: |
          podman cp microos.kiwi opensuse-container:/root/microos.kiwi

      - name: Build openSUSE Micro OS Image
        run: |
          podman exec opensuse-container kiwi-ng system build --description /root/microos.kiwi

      - name: Log in to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GHCR
        run: |
          podman load -i /var/lib/containers/storage/overlay-containers/*/userdata/opensuse-rootfs.tar
          podman tag opensuse/microos:latest ghcr.io/your-username/microos-image:latest
          podman push ghcr.io/your-username/microos-image:latest

      - name: Clean up
        run: |
          podman stop opensuse-container
          podman rm opensuse-container
