name: Build OSTree Image
on:
  push:
    branches:
      - main  # Modifier selon votre branche

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Create OSTree Directory
        run: |
          mkdir -p ${{ github.workspace }}/ostree-repo
          mkdir -p ${{ github.workspace }}/custom-root
          chmod -R 777 ${{ github.workspace }}/ostree-repo
          chmod -R 777 ${{ github.workspace }}/custom-root
          
      - name: Create OSTree Repository
        run: |
          ostree init --repo=${{ github.workspace }}/ostree-repo


      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build OSTree Image
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/ostree-repo:/repo \
            -v ${{ github.workspace }}/custom-root:/mnt \
            opensuse/tumbleweed /bin/sh -c '
            zypper --non-interactive install ostree neofetch && \
            ostree commit --repo=/repo --branch=ma_branche --tree=/mnt
            '

      - name: Log in to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and Push Image to GHCR
        run: |
          docker tag ostree-builder ghcr.io/${{ github.repository_owner }}/ostree-image:latest
          docker push ghcr.io/${{ github.repository_owner }}/ostree-image:latest
