name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish Image
        env:
          GHCR_USERNAME: ${{ github.actor }}
          GHCR_REPOSITORY: ${{ github.repository }}
          GHCR_TAG: latest
        run: |
          GHCR_USERNAME_LOWER=$(echo "${GHCR_USERNAME}" | tr '[:upper:]' '[:lower:]')
          docker build --build-arg GHCR_USERNAME=$GHCR_USERNAME_LOWER --build-arg GHCR_REPOSITORY=$GHCR_REPOSITORY --build-arg GHCR_TAG=$GHCR_TAG -t ghcr.io/$GHCR_USERNAME_LOWER/$GHCR_REPOSITORY:$GHCR_TAG
          docker push ghcr.io/$GHCR_USERNAME_LOWER/$GHCR_REPOSITORY:$GHCR_TAG
