name: Build OSTree Image
on:
  push:
    branches:
      - main
      
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.txt"
  # Build when manually triggering this workflow for a branch. This allows you
  # to build any branch, even if it's not listed in the automated triggers above.
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create OSTree Directory
        run: |
          mkdir -p ${{ github.workspace }}/ostree-repo
          mkdir -p ${{ github.workspace }}/custom-root
          chmod -R 777 ${{ github.workspace }}/ostree-repo
          chmod -R 777 ${{ github.workspace }}/custom-root

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build OSTree Image
        run: |
          docker run --rm \
          -v ${{ github.workspace }}/ostree-repo:/repo \
          -v ${{ github.workspace }}/custom-root:/mnt \
          opensuse/tumbleweed /bin/sh -c '
          zypper --non-interactive install ostree && \
          zypper --non-interactive addrepo --refresh https://download.opensuse.org/tumbleweed/repo/oss oss && \
          zypper --non-interactive refresh && \
          zypper --non-interactive --root=/mnt install neofetch && \
          ostree init --repo=/repo && \
          ostree commit --repo=/repo --branch=ma_branche --tree=dir=/mnt
          '

      - name: Log in to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Convert username to lowercase
        id: convert_username
        run: echo "::set-output name=username_lowercase::${{ github.actor }}" | tr '[:upper:]' '[:lower:]'

      - name: Tag and Push Image to GHCR
        run: |
          docker tag opensuse/tumbleweed ghcr.io/${{ steps.convert_username.outputs.username_lowercase }}/ostree-image:latest
          docker push ghcr.io/${{ steps.convert_username.outputs.username_lowercase }}/ostree-image:latest
